version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: ${APP_CONTAINER_NAME}
    env_file:
      - .env
    tty: true 
    depends_on:
      db:
        condition: service_healthy
    ports:
      - ${APP_PORT}:8080
    command: ./main
  db:
    image: postgres:13.3
    restart: always
    container_name: ${DB_HOST}
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-store:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: "pg_isready -U postgres -d ocpi || exit 1"
  swagger-ui:
    image: swaggerapi/swagger-ui
    restart: always
    container_name: "swagger-ui"
    ports:
      - "8001:8080"
    environment:
      SWAGGER_JSON_URL: http://localhost:${APP_PORT}/ocpi/diskymg/2.2/openapi-spec.yaml

volumes:
  db-store:
